apiVersion: batch/v1
kind: Job
metadata:
  name: td-train
  namespace: transit-delay
spec:
  template:
    metadata:
      labels:
        app: td-train
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: REPLACE_WITH_ECR/td-train:0.1
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["sh", "-c"]
          args:
            - >
              python train.py
              --input /app/data/sample_bus_events.json
              --output-dir /tmp/models
              --model-bucket ${MODEL_BUCKET}
          env:
            - name: AWS_REGION
              value: eu-central-1
            - name: MODEL_BUCKET
              value: replace-me-model-bucket
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
  backoffLimit: 1
