-- Replace REPLACE_ME_BUCKET and prefix values before running in Athena.

CREATE DATABASE IF NOT EXISTS nyc_heat_risk;

CREATE EXTERNAL TABLE IF NOT EXISTS nyc_heat_risk.logistic_regression_scored (
  building_id string,
  building_bbl string,
  calendar_date string,
  borough string,
  incident_address string,
  complaint_count int,
  unique_request_count int,
  no_heat_count int,
  hot_water_problem_count int,
  lag_1_complaints int,
  rolling_3d_complaints int,
  rolling_7d_complaints int,
  rolling_7d_request_count int,
  complaint_day_count_prior int,
  cumulative_complaints_prior int,
  cumulative_request_count_prior int,
  prior_max_daily_complaints int,
  days_since_last_complaint int,
  next_day_complaint_count int,
  next_day_label_available int,
  surge_flag int,
  management_program string,
  building_zip string,
  community_board string,
  census_tract string,
  registration_active_flag int,
  heat_sensor_program_flag int,
  heat_sensor_active_flag int,
  heat_sensor_unit_count int,
  total_linked_violation_count int,
  open_linked_violation_count int,
  unit_count_proxy int,
  weather_station_count int,
  weather_avg_temp_c double,
  weather_max_temp_c double,
  weather_min_temp_c double,
  weather_prcp_mm_mean double,
  weather_prcp_mm_max double,
  weather_wind_mps_mean double,
  weather_heating_degree_c double,
  weather_freezing_station_count int,
  weather_freezing_any_flag int,
  weather_temp_drop_c double,
  weather_cold_shock_flag int,
  target int,
  unit_count_effective int,
  open_violation_per_unit double,
  rolling_7d_complaints_per_unit double,
  days_since_last_complaint_capped int,
  no_heat_share double,
  hot_water_share double,
  weather_severity_index double,
  model_probability double,
  model_threshold double,
  model_prediction int,
  data_split string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar' = '\"',
  'escapeChar' = '\\'
)
STORED AS TEXTFILE
LOCATION 's3://REPLACE_ME_BUCKET/nyc-heat-risk/latest/scored/'
TBLPROPERTIES ('skip.header.line.count'='1');

CREATE EXTERNAL TABLE IF NOT EXISTS nyc_heat_risk.inspection_priority_latest_day (
  building_id string,
  building_bbl string,
  calendar_date string,
  borough string,
  incident_address string,
  complaint_count int,
  unique_request_count int,
  no_heat_count int,
  hot_water_problem_count int,
  lag_1_complaints int,
  rolling_3d_complaints int,
  rolling_7d_complaints int,
  rolling_7d_request_count int,
  complaint_day_count_prior int,
  cumulative_complaints_prior int,
  cumulative_request_count_prior int,
  prior_max_daily_complaints int,
  days_since_last_complaint int,
  next_day_complaint_count int,
  next_day_label_available int,
  surge_flag int,
  management_program string,
  building_zip string,
  community_board string,
  census_tract string,
  registration_active_flag int,
  heat_sensor_program_flag int,
  heat_sensor_active_flag int,
  heat_sensor_unit_count int,
  total_linked_violation_count int,
  open_linked_violation_count int,
  unit_count_proxy int,
  weather_station_count int,
  weather_avg_temp_c double,
  weather_max_temp_c double,
  weather_min_temp_c double,
  weather_prcp_mm_mean double,
  weather_prcp_mm_max double,
  weather_wind_mps_mean double,
  weather_heating_degree_c double,
  weather_freezing_station_count int,
  weather_freezing_any_flag int,
  weather_temp_drop_c double,
  weather_cold_shock_flag int,
  target int,
  unit_count_effective int,
  open_violation_per_unit double,
  rolling_7d_complaints_per_unit double,
  days_since_last_complaint_capped int,
  no_heat_share double,
  hot_water_share double,
  weather_severity_index double,
  model_probability double,
  model_threshold double,
  model_prediction int,
  data_split string,
  inspection_priority_rank int
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar' = '\"',
  'escapeChar' = '\\'
)
STORED AS TEXTFILE
LOCATION 's3://REPLACE_ME_BUCKET/nyc-heat-risk/latest/priority/'
TBLPROPERTIES ('skip.header.line.count'='1');
